version: 0.0
os: linux
files:
  - source: /packages/mesos-dns-v0.5.2-linux-amd64
    destination: /usr/bin/
  - source: /packages/vault_0.5.2_linux_amd64.zip
    destination: /tmp/
permissions:
  - object: /usr/bin/mesos-dns-v0.5.2-linux-amd64
    owner: root
    group: root
    mode: 755
hooks:
  AfterInstall:
    - location: scripts/docker_install.sh
      timeout: 300
      runas: root
    - location: /scripts/mesos_agent_install.sh
      timeout: 300
      runas: root
    - location: scripts/dns-services.sh
      timeout: 300
      runas: root
    - location: scripts/vault.sh
      timeout: 300
      runas: root
